// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OnlineExamination.Entities;

[PrimaryKey("QuestionId", "Value")]
public partial class Answer
{
    [Key]
    [Column("Question_Id")]
    public int QuestionId { get; set; }

    [Key]
    [StringLength(50)]
    [Unicode(false)]
    public string Value { get; set; }

    [ForeignKey("QuestionId")]
    [InverseProperty("Answers")]
    public virtual Question Question { get; set; }
}