// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OnlineExamination.Entities;

[PrimaryKey("QuestionId", "ChoiceNumber")]
public partial class Choice
{
    [Key]
    [Column("Question_Id")]
    public int QuestionId { get; set; }

    [Key]
    [Column("Choice_Number")]
    [StringLength(50)]
    [Unicode(false)]
    public string ChoiceNumber { get; set; }

    [Required]
    [StringLength(500)]
    [Unicode(false)]
    public string Content { get; set; }

    [ForeignKey("QuestionId")]
    [InverseProperty("Choices")]
    public virtual Question Question { get; set; }
}