// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OnlineExamination.Entities;

public partial class Course
{
    [Key]
    [Column("Course_Id")]
    public int CourseId { get; set; }

    [Column("Course_Name")]
    [StringLength(50)]
    [Unicode(false)]
    public string CourseName { get; set; }

    [InverseProperty("Course")]
    public virtual ICollection<Exam> Exams { get; set; } = new List<Exam>();

    [InverseProperty("Course")]
    public virtual ICollection<Question> Questions { get; set; } = new List<Question>();

    [InverseProperty("Course")]
    public virtual ICollection<StudentCourse> StudentCourses { get; set; } = new List<StudentCourse>();

    [InverseProperty("Course")]
    public virtual ICollection<Topic> Topics { get; set; } = new List<Topic>();

    [ForeignKey("CourseId")]
    [InverseProperty("Courses")]
    public virtual ICollection<Instructor> Ins { get; set; } = new List<Instructor>();
}