// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OnlineExamination.Entities;

public partial class Department
{
    [Key]
    [Column("Department_ID")]
    public int DepartmentId { get; set; }

    [Column("Department_Name")]
    [StringLength(50)]
    [Unicode(false)]
    public string DepartmentName { get; set; }

    [Column("Dept_Description")]
    [StringLength(200)]
    [Unicode(false)]
    public string DeptDescription { get; set; }

    [InverseProperty("Dept")]
    public virtual ICollection<Instructor> Instructors { get; set; } = new List<Instructor>();

    [InverseProperty("Dept")]
    public virtual ICollection<Student> Students { get; set; } = new List<Student>();
}