// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OnlineExamination.Entities;

public partial class Exam
{
    [Key]
    [Column("Exam_Id")]
    public int ExamId { get; set; }

    [Column("Exam_Name")]
    [StringLength(50)]
    [Unicode(false)]
    public string ExamName { get; set; }

    [Required]
    [Column("Exam_Duration")]
    [StringLength(50)]
    [Unicode(false)]
    public string ExamDuration { get; set; }

    [Column("Course_Id")]
    public int CourseId { get; set; }

    [ForeignKey("CourseId")]
    [InverseProperty("Exams")]
    public virtual Course Course { get; set; }

    [InverseProperty("Exam")]
    public virtual ICollection<StudentAnswerInExam> StudentAnswerInExams { get; set; } = new List<StudentAnswerInExam>();

    [ForeignKey("ExamId")]
    [InverseProperty("Exams")]
    public virtual ICollection<Question> Questions { get; set; } = new List<Question>();
}