// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OnlineExamination.Entities;

public partial class Instructor
{
    [Key]
    [Column("Instructor_Id")]
    public int InstructorId { get; set; }

    [Column("Instructor_Name")]
    [StringLength(50)]
    [Unicode(false)]
    public string InstructorName { get; set; }

    [Column("Dept_Id")]
    public int? DeptId { get; set; }

    [ForeignKey("DeptId")]
    [InverseProperty("Instructors")]
    public virtual Department Dept { get; set; }

    [ForeignKey("InsId")]
    [InverseProperty("Ins")]
    public virtual ICollection<Course> Courses { get; set; } = new List<Course>();
}