// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OnlineExamination.Entities;

public partial class Question
{
    [Key]
    [Column("Question_Id")]
    public int QuestionId { get; set; }

    public int Grade { get; set; }

    [Required]
    [StringLength(400)]
    [Unicode(false)]
    public string Content { get; set; }

    [Required]
    [Column("Question_Type")]
    [StringLength(100)]
    [Unicode(false)]
    public string QuestionType { get; set; }

    [Column("Course_Id")]
    public int CourseId { get; set; }

    [InverseProperty("Question")]
    public virtual ICollection<Answer> Answers { get; set; } = new List<Answer>();

    [InverseProperty("Question")]
    public virtual ICollection<Choice> Choices { get; set; } = new List<Choice>();

    [ForeignKey("CourseId")]
    [InverseProperty("Questions")]
    public virtual Course Course { get; set; }

    [InverseProperty("Question")]
    public virtual ICollection<StudentAnswerInExam> StudentAnswerInExams { get; set; } = new List<StudentAnswerInExam>();

    [ForeignKey("QuestionId")]
    [InverseProperty("Questions")]
    public virtual ICollection<Exam> Exams { get; set; } = new List<Exam>();
}