// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OnlineExamination.Entities;

[PrimaryKey("StudentId", "CourseId")]
[Table("Student_Courses")]
public partial class StudentCourse
{
    [Key]
    [Column("Student_Id")]
    public int StudentId { get; set; }

    [Key]
    [Column("Course_Id")]
    public int CourseId { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? StudentGrade { get; set; }

    [ForeignKey("CourseId")]
    [InverseProperty("StudentCourses")]
    public virtual Course Course { get; set; }

    [ForeignKey("StudentId")]
    [InverseProperty("StudentCourses")]
    public virtual Student Student { get; set; }
}