// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OnlineExamination.Entities;

public partial class Student
{
    [Key]
    [Column("Student_Id")]
    public int StudentId { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    public string Fname { get; set; }

    [Column("LName")]
    [StringLength(10)]
    [Unicode(false)]
    public string Lname { get; set; }

    public int? Age { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string Email { get; set; }

    [Column("Dept_Id")]
    public int? DeptId { get; set; }

    [ForeignKey("DeptId")]
    [InverseProperty("Students")]
    public virtual Department Dept { get; set; }

    [InverseProperty("Student")]
    public virtual ICollection<StudentAnswerInExam> StudentAnswerInExams { get; set; } = new List<StudentAnswerInExam>();

    [InverseProperty("Student")]
    public virtual ICollection<StudentCourse> StudentCourses { get; set; } = new List<StudentCourse>();
}