// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OnlineExamination.Entities;

[PrimaryKey("TopicId", "CourseId")]
[Table("Topic")]
public partial class Topic
{
    [Key]
    [Column("Topic_Id")]
    public int TopicId { get; set; }

    [Key]
    [Column("Course_Id")]
    public int CourseId { get; set; }

    [Column("Topic_Name")]
    [StringLength(50)]
    [Unicode(false)]
    public string TopicName { get; set; }

    [ForeignKey("CourseId")]
    [InverseProperty("Topics")]
    public virtual Course Course { get; set; }
}